services:
  - name: laravel-app
    type: web
    runtime: docker
    repo: https://github.com/AEGcarlosfigueroa/laravel-test2
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
        name: LaravelTest
        property: postgresql://laravelTest_owner:npg_6cWuHIGTz2AX@ep-still-base-abthmx6a-pooler.eu-west-2.aws.neon.tech/laravelTest?sslmode=require
