services:
  - name: laravel-app
    type: web
    runtime: docker
    repo: https://github.com/AEGcarlosfigueroa/laravel-test2
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase: ep-still-base-abthmx6a-pooler.eu-west-2.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase: laravelTest
      - key: DB_USERNAME
        fromDatabase: laravelTest_owner
      - key: DB_PASSWORD
        fromDatabase: npg_6cWuHIGTz2AX
